### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by Flypotter** [badeggg/mock-api#9]
### 模拟websocket

​	和http协议同属于应用层协议，都是机遇tcp连接的协议，可以共享同一端口，使用ws模块来启动一个websocket的服务。（试过wxpress-ws中间件的方式，没有回调函数没有执行但连接是成功的，可能和其他注册的中间件有冲突或者其他细节没有注意到）

​	初步判断应该无法像注册http中间件的方式为ws请求进行处理，可以在mock.js中只进行启动服务，将处理函数抽离出去（考虑是否放在.../middlewares/mapToRes中）

​	使用mock.js模拟ws响应配置可以为对应请求路径的文件夹下一个js文件，该文件导出一个res和interval，分别表示返回的结果和结果发送的间隔时间，其中res只允许为返回值为array的function或者array，interval只允许为number。直接执行，将数组结果按照间隔用定时器发送。

​	加入特定字段暂时不清楚

**Comment by badeggg** [comment]
和我想要的东西还是有一点距离的。

mock websocket 是一个很重要、较复杂的功能点，说实话我暂时不放心把这个重要复杂的功能直接交给你来写代码。本意是希望看下你有哪些想法，能否碰撞出一些火花，并非直接交由你来写代码。当然这不妨碍你自己 hack.  happy hacking ;-)

如果感兴趣的话：
- gleam 文件中记录了许多我想做但还没做的小的改进/功能，可以看下那里有没有感兴趣的想实现的东西（那里记录得有点随意可能看起来比较费劲）
- 或者直接联系我看有哪些小的功能点想实现。

**Comment by badeggg** [comment]
作者名单会加上你
